# -*- coding: utf-8 -*-
###
#"""ddgsearch.ipynb

# Automatically generated by Colaboratory.

#  Original file is located at
   # https://colab.research.google.com/drive/1G6dOAe_c4sdveUzJZHm8J795RxxvZkvm

# MRKL Agent for LLMs

#key : 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

#pip install streamlit openai langchain

#pip install duckduckgo-search
###


import os
from langchain.llms import openai
from langchain.agents import load_tools , initialize_agent , AgentType
from langchain.callbacks import StreamlitCallbackHandler
import streamlit as st

llm = OpenAI ( temperature= 0 , streaming= True , openai_api_key= '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')
# Agents = prompt chain agent
#duckduckgo  = can search anything

tools = load_tools(
    ["ddg-search"]
)
agent = initialize_agent(
    tools = tools,
    llm = llm,
    agent = AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION
)

from langchain.callbacks.streamlit import streamlit_callback_handler
if prompt :=st.chat_input():
  st.chat_message("user").write(prompt)
  with st.chat_message("assistant"):
    st.write(" Thinking ...")
    st_callback = streamlit_callback_handler(st.container())
    response = agent.run(prompt, callbacks= [st_callback])
    st.write(response)

